apiVersion: v2
dependencies:
- name: cert-manager
  repository: https://charts.jetstack.io
  version: 1.18.2
description: A Helm chart for Kubernetes
name: PXCertManager
type: application
version: 1.0.3
