apiVersion: v2
appVersion: 5.14.2
description: 'This is a Helm chart for deploying MetaDefender Core (https://www.opswat.com/products/metadefender/core)
  in a Kubernetes cluster.   Release Notes - Environment variables to migrate processing
  history (Pre-steps needed) - Environment variables to enable Licensing Cleanup and
  examples for Role/Rolebinding - Fixed warning of kubernetes.io/ingress.class annotation
  for AWS and Azure. Added control flag to still use it for GCP '
name: mdcore
type: application
version: 5.14.2
