apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: envoy-gateway-system
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  secretName: wildcard-cert
  issuerRef:
    name: letsencrypt-dns01
    kind: ClusterIssuer
  dnsNames:
{{- range .Values.certificate.dnsNames }}
  - {{ . | quote }}
{{- end }}
