apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-kv
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  provider:
    vault:
      server: "http://vault.vault.svc:8200"
      path: "kv"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: {{ .Values.vault.role | quote }}
          serviceAccountRef:
            name: {{.Values.serviceAccount.name }}
