apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret1.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"

spec:
  refreshInterval: "1h"

  secretStoreRef:
    name: {{ .Values.externalSecret1.secretStoreName }}
    kind: ClusterSecretStore

  target:
    name: {{ .Values.externalSecret1.targetName }}
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque

  data:
    - secretKey: REDIS_USERNAME
      remoteRef:
        key: {{ .Values.externalSecret1.remoteKey }}
        property: username

    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecret1.remoteKey }}
        property: password
