apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.redisSecretAccess.bindingName | default "harbor-eso-secret-reader-binding" }}
  namespace: {{ .Values.redisSecretAccess.sourceNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.redisSecretAccess.roleName | default "harbor-eso-secret-reader" }}
