apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.redisSecretAccess.roleName | default "harbor-eso-secret-reader" }}
  namespace: {{ .Values.redisSecretAccess.sourceNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get","list","watch"]
