apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-route
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  parentRefs:
  - name: {{ .Values.gateway.name }}
    namespace: {{ .Values.gateway.namespace }}
  hostnames:
  - {{ .Values.harbor.externalURL | trimPrefix "https://" | trimPrefix "http://" | quote }}
  rules:
  - backendRefs:
    - name: {{ .Release.Name }}
      port: {{ .Values.gateway.port | default 80 }}
