{{- if and .Values.secrets .Values.secrets.createClusterSecretStore }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ include "mdss.fullname" . }}-vault
spec:
  provider:
    vault:
      server: {{ .Values.secrets.vault.address | quote }}
      path: {{ .Values.secrets.vault.path | default "kv" | quote }}
      version: {{ .Values.secrets.vault.version | default "v2" | quote }}
      auth:
        kubernetes:
          mountPath: {{ .Values.secrets.vault.authMountPath | default "kubernetes" | quote }}
          role: {{ .Values.secrets.vault.role | quote }}
          serviceAccountRef:
            name: {{ .Values.secrets.vault.serviceAccount | default "my-external-secrets" | quote }}
            namespace: {{ .Values.secrets.vault.serviceAccountNamespace | default "eso" | quote }}
{{- end }}
