{{- if and .Values.secrets .Values.secrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "mdss.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.secrets.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ include "mdss.fullname" . }}-vault
    kind: ClusterSecretStore
  target:
    name: {{ include "mdss.fullname" . }}-secret
    creationPolicy: Owner
  data:
    {{- range .Values.secrets.items }}
    - secretKey: {{ .k8sKey }}
      remoteRef:
        key: {{ .remoteKey }}
        property: {{ .property }}
    {{- end }}
{{- end }}
