apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "technitium.fullname" . }}-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "technitium.name" . }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- else if (eq .Values.persistence.storageClass "") }}
  storageClassName: ""
  {{- end }}
