apiVersion: v2
dependencies:
- name: metallb
  repository: https://metallb.github.io/metallb
  version: 0.15.2
description: A Helm chart for Kubernetes
name: pxmetallb
type: application
version: 1.0.0
